// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4RrCaElHPzK1cq9f6tBCRzkAdcnhgahs',
    appId: '1:170498746328:web:831f9301f0e759887834ad',
    messagingSenderId: '170498746328',
    projectId: 'fir-flutter-codelab-2acb5',
    authDomain: 'fir-flutter-codelab-2acb5.firebaseapp.com',
    databaseURL: 'https://fir-flutter-codelab-2acb5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-2acb5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCes8fDGthVPKZUob34V1B8b6dTKO5n1Ag',
    appId: '1:170498746328:android:f11fe254dc203df37834ad',
    messagingSenderId: '170498746328',
    projectId: 'fir-flutter-codelab-2acb5',
    databaseURL: 'https://fir-flutter-codelab-2acb5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-2acb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUzJzjcx0Ul1q6Xst4M4hyiFM00oc8Pv8',
    appId: '1:170498746328:ios:1515c4da34a36bce7834ad',
    messagingSenderId: '170498746328',
    projectId: 'fir-flutter-codelab-2acb5',
    databaseURL: 'https://fir-flutter-codelab-2acb5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-2acb5.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUzJzjcx0Ul1q6Xst4M4hyiFM00oc8Pv8',
    appId: '1:170498746328:ios:63bfc94e699203067834ad',
    messagingSenderId: '170498746328',
    projectId: 'fir-flutter-codelab-2acb5',
    databaseURL: 'https://fir-flutter-codelab-2acb5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-2acb5.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
